server:
  port: 9192
spring:
  application:
    name: order-service
  cloud:
    nacos: #配置nacos
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
